### ISSUE TITLE
Mix fails, when running lazyasdf from non default directory

### ISSUE THREAD

**Issue by PeterUstinox** [mhanberg/lazyasdf#10]
running on linux starting lazyasdf via `bin/lazyasdf` works fine. But when running it from any other directory Mix fails, i.e. in the `bin` folder itself by running `lazyasdf`, since it seems like Mix is expecting a `mix.exs` file there:
```
** (Mix) Cannot execute "mix run" without a Mix.Project, please ensure you are running Mix in a directory with a mix.exs file or pass the --no-mix-exs option
```

I have no knowledge of Mix etc. but is there a workaround to this?

**Comment by mhanberg** [comment]
Assuming you are trying to use lazyasdf and just need to build it from source, I would suggest you run bin/setup, then compile the release binary with `MIX_ENV=prod mix release`, and then symlink to the `burrito_out/lazyadsf_<your target>` from somewhere on your path (or move and rename the binary to somewhere on your path)

There's a chance you'll have to add a linux target to the mix.exs file as well `linux: [os: :linux, cpu: :x86_64],`, which would go below line 30.

**Comment by PeterUstinox** [comment]
Thanks @mhanberg!

It all worked wonderfully. The linux target was needed. 
Looking forward to using this, thanks!
