### ISSUE TITLE
Set max-height for panes

### ISSUE THREAD

**Issue by kiskoza** [mhanberg/lazyasdf#3]
Hi. I checked out your amazing new tool, and found a small issue: I'm using too much asdf and it can't fit on my screen. Can we restrict the size of the panes? (Also it would be nice to have an indicator that you can scroll in a pane)

![image](https://user-images.githubusercontent.com/1900366/223387299-83088567-f5f4-4e21-8886-d7d3910f41b5.png)

**Comment by mhanberg** [comment]
> Also it would be nice to have an indicator that you can scroll in a pane)

scroll bars are an upstream contribution to the ratatouille library that i need to make, but i can fix the pane sizing.

**Comment by mhanberg** [comment]
Closed by #9
