### ISSUE TITLE
could not compile dependency :ex_termbox

### ISSUE THREAD

**Issue by mxgrn** [mhanberg/lazyasdf#7]
Might not be a proper place to report this, but I was following the [blog post](https://www.mitchellhanberg.com/introducing-lazyasdf-a-tui-for-the-asdf-version-manager/) and as I was trying to run the Todos example, got this:

```
make: *** [c_src/termbox/build/src/libtermbox.a] Error 2
could not compile dependency :ex_termbox, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_termbox", update it with "mix deps.update ex_termbox" or clean it with "mix deps.clean ex_termbox"
** (Mix.Error) Could not compile with "make" (exit status: 2).
```

Looked into [ex_termbox](https://github.com/ndreynolds/ex_termbox) and termbox itself, just to learn that the latter is no longer maintained. Any hints how to get this right?

Thanks a lot!

**Comment by mhanberg** [comment]
I would ensure you have an unversioned python executable in your path. So `python` not `python3`

**Comment by mxgrn** [comment]
Both `python` and `python3` are in the path, both pointing to Python 3.11.1.

**Comment by mhanberg** [comment]
Could you try with Python3.9?

In the future I hope to migrate to termbox2, which doesn't have any python infrastructure.
