### ISSUE TITLE
"zig plugin is not installed"

### ISSUE THREAD

**Issue by adolfont** [mhanberg/lazyasdf#8]
Hi,
I followed the steps on "Installation" "Using git" and "asdf install" returned "zig plugin is not installed".

> asdf plugin-add zig https://github.com/asdf-community/asdf-zig.git

solved my issue but maybe this issue will help other users.  

Then, after running

> mix run --no-halt

I got:

```
make: *** [Makefile:19: c_src/termbox/build/src/libtermbox.a] Error 127
could not compile dependency :ex_termbox, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ex_termbox", update it with "mix deps.update ex_termbox" or clean it with "mix deps.clean ex_termbox"
==> lazyasdf
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".
```

**Comment by mhanberg** [comment]
Are you still stuck on that last step?

**Comment by mhanberg** [comment]
I updated the README and added a bin script, so you can pull once more and run `bin/setup` and it should ensure you have all the right asdf plugins and versions installed.

**Comment by adolfont** [comment]
Thanks! It worked!

I did something wrong, though.
I saw that there was version 25.3 of Erlang and uninstalled, with lazyasdf, version 25.2.3. Lazyasdf stopped working, obviously, because it uses Erlang 25.2.3. Maybe lazyasdf should prohibit bad users such as myself from doing something like this.
